---
title: "TidyDataPractice"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, warning = F, message = F}
library(dplyr)
library(tidyr)
```
Read in data from [Mike Byerly. 2016. Alaska commercial salmon catches by management region (1886- 1997). urn:node:GOA. df35b.304.2.](https://knb.ecoinformatics.org/#view/df35b.304.2)

```{r}
catch_df <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl"),
                    stringsAsFactors = FALSE)
head(catch_df)
```
```{r}
catch_df <- catch_df %>% 
  select(-All, -notesRegCode)

head(catch_df)
```
Transposed data using "gather" and renamed the column to reflect units
```{r}
catch_df <- catch_df %>% 
  gather(key ="species", value = "catch", -Region, -Year) %>% 
  rename(catch_thousands = catch)
  
head(catch_df)
```

```{r}
catch_integers <- as.integer(catch_df$catch_thousands)

i <- which(is.na(catch_integers) == T)

catch_df$catch_thousands[i]
```
1) turn "I" into 1 in the catch_thousands column
2) coerce catch_thousand into integer type
3) convert catch_thousands to catch

```{r}
catch_df <- catch_df %>% 
  mutate(catch_thousands = ifelse(catch_thousands == "I", 1, catch_thousands)) %>% 
  mutate(catch_thousands =as.integer(catch_thousands)) %>% 
  mutate(catch = catch_thousands*1000)

tail(catch_df)
```

#split_apply_combine

```{r}
catch_summarizes <- catch_df %>% 
  group_by(Region) %>% 
  summarise(mean_catch = mean(catch))

tail(catch_summarizes, 15)
```

```{r}
catch_Year <- catch_df %>% 
  filter(Year > 1980 & species == "Chinook") %>% 
  group_by(Year) %>% 
  summarise(sum_catch_Chinook = sum(catch))
  
print(catch_Year)
```
```{r}
catch_summarizes_region_species <- catch_df %>% 
  group_by(Region, species) %>% 
  summarise(mean_catch = mean(catch, na.rm = T),
            num_obs = n()) %>% 
  #Filter for Chinook
  filter(species == "Chinook")
  

print(catch_summarizes_region_species)
```

read in region deffinition file

```{r}
region_defs <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.303.1", method = "libcurl"),
                        stringsAsFactors = FALSE)

head(region_defs)
```

```{r}
region_defs <- region_defs %>% 
  select(code, mgmtArea)

head(region_defs)
```
```{r}
catch_joined <- left_join(catch_df, region_defs, by = c("Region" = "code")) %>% 
  select(Year, species, catch_thousands, mgmtArea) %>% 
  group_by(mgmtArea) %>% 
  filter(catch_thousands > 10000)


print(catch_joined)
```


























